version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mariadb:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mariadb/data/db:/var/lib/mysql
    env_file:
      - ./docker/mariadb/env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=adminer.local
    links:
      - mariadb:db

  app:
    build:
      context: ./docker/app
    volumes:
      - ./:/var/www/html
      - ./docker/app/data/apache/logs/:/var/log/apache2
    environment:
      - VIRTUAL_HOST=app.presentator.local,api.presentator.local
    links:
      - mariadb:db
